Repository dsaidgovsg/terraform-modules, pull requests merged in 2020-08, with the labels that each got.

#256 fix(aws): upgrade to use non-deprecated attributes
  modules/aws-auth/INOUT.md
  modules/aws-auth/versions.tf
  modules/core/INOUT.md
  modules/core/elb.tf
  modules/core/versions.tf
  modules/curator/INOUT.md
  modules/curator/versions.tf
  modules/ecr/INOUT.md
  modules/ecr/route53.tf
  modules/ecr/versions.tf
  modules/efs/INOUT.md
  modules/efs/versions.tf
  modules/elasticsearch/INOUT.md
  modules/elasticsearch/versions.tf
  modules/elasticsearch_post/redirect.tf
  modules/fluentd/INOUT.md
  modules/fluentd/versions.tf
  modules/grafana/INOUT.md
  modules/grafana/versions.tf
  modules/lambda-api-gateway/INOUT.md
  modules/lambda-api-gateway/api-gateway.tf
  modules/lambda-api-gateway/versions.tf
  modules/nexus/INOUT.md
  modules/nexus/versions.tf
  modules/nomad-clients/INOUT.md
  modules/nomad-clients/versions.tf
  modules/prometheus/INOUT.md
  modules/prometheus/versions.tf
  modules/traefik/INOUT.md
  modules/traefik/main.tf
  modules/traefik/versions.tf
  modules/vault-auto-unseal/INOUT.md
  modules/vault-auto-unseal/versions.tf
Labels: fix, size/M

#258 fix(prometheus): remove deprecated var for new packer version
  modules/prometheus/README.md
  modules/prometheus/packer/ami/packer.json
  modules/prometheus/packer/data/packer.json
Labels: chore, size/S

#255 refactor(fluentd): make fluentd_pre and fluentd_new
  modules/fluentd_new/INOUT.md
  modules/fluentd_new/README.md
  modules/fluentd_new/data.tf
  modules/fluentd_new/elb.tf
  modules/fluentd_new/main.tf
  modules/fluentd_new/modules/fluentd_base/INOUT.md
  modules/fluentd_new/modules/fluentd_base/main.tf
  modules/fluentd_new/modules/fluentd_base/outputs.tf
  modules/fluentd_new/modules/fluentd_base/sg.tf
  modules/fluentd_new/modules/fluentd_base/variables.tf
  modules/fluentd_new/outputs.tf
  modules/fluentd_new/user_data.sh
  modules/fluentd_new/variables.tf
  modules/fluentd_pre/INOUT.md
  modules/fluentd_pre/README.md
  modules/fluentd_pre/main.tf
  modules/fluentd_pre/outputs.tf
  modules/fluentd_pre/packer/packer.json
  modules/fluentd_pre/packer/site.yml
  modules/fluentd_pre/s3.tf
  modules/fluentd_pre/templates/fluent.conf
  modules/fluentd_pre/variables.tf
  roles/td-agent/files/run-td-agent.sh
Labels: refactor, size/XXL

#257 chore(fluentd): redirect logs from hashi services
  modules/core/packer/consul/packer.json
  modules/core/packer/consul/site.yml
  modules/core/packer/nomad_clients/packer.json
  modules/core/packer/nomad_clients/site.yml
  modules/core/packer/nomad_servers/packer.json
  modules/core/packer/nomad_servers/site.yml
  modules/core/packer/vault/packer.json
  modules/core/packer/vault/site.yml
  modules/nexus/packer/ami/packer.json
  modules/nexus/packer/ami/site.yml
  modules/nexus/packer/ami/td-agent-vars.yml
  modules/prometheus/packer/ami/packer.json
  modules/prometheus/packer/ami/site.yml
  modules/prometheus/packer/ami/td-agent-vars.yml
  modules/td-agent/config/consul/td-agent-vars.yml
  modules/td-agent/config/nomad_clients/td-agent-vars.yml
  modules/td-agent/config/nomad_servers/td-agent-vars.yml
  modules/td-agent/config/template/td-agent.conf
  modules/td-agent/config/vault/td-agent-vars.yml
  roles/td-agent/defaults/main.yml
  roles/td-agent/tasks/main.yml
Labels: BREAKING CHANGE, chore, size/M
